### ISSUE TITLE
cannot install nexcsi

### ISSUE THREAD

**Issue by IceNotCold** [nexmonster/nexcsi#3]
My xubuntu 16.04 installed python 2.7 and python 3.8. When I excute "pin install nexcsi", it gets many errors:

ERROR: Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pip/_internal/cli/base_command.py", line 223, in _main
    status = self.run(options, args)
  File "/usr/local/lib/python2.7/dist-packages/pip/_internal/cli/req_command.py", line 180, in wrapper
    return func(self, options, args)
  File "/usr/local/lib/python2.7/dist-packages/pip/_internal/commands/install.py", line 271, in run
    session = self.get_default_session(options)
  File "/usr/local/lib/python2.7/dist-packages/pip/_internal/cli/req_command.py", line 78, in get_default_session
    self._session = self.enter_context(self._build_session(options))
  File "/usr/local/lib/python2.7/dist-packages/pip/_internal/cli/req_command.py", line 95, in _build_session
    index_urls=self._get_index_urls(options),
  File "/usr/local/lib/python2.7/dist-packages/pip/_internal/network/session.py", line 248, in __init__
    self.headers["User-Agent"] = user_agent()
  File "/usr/local/lib/python2.7/dist-packages/pip/_internal/network/session.py", line 131, in user_agent
    zip(["name", "version", "id"], distro.linux_distribution()),
  File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/distro.py", line 125, in linux_distribution
    return _distro.linux_distribution(full_distribution_name)
  File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/distro.py", line 681, in linux_distribution
    self.version(),
  File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/distro.py", line 741, in version
    self.lsb_release_attr('release'),
  File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/distro.py", line 903, in lsb_release_attr
    return self._lsb_release_info.get(attribute, '')
  File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/distro.py", line 556, in __get__
    ret = obj.__dict__[self._fname] = self._f(obj)
  File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/distro.py", line 1014, in _lsb_release_info
    stdout = subprocess.check_output(cmd, stderr=devnull)
  File "/usr/lib/python2.7/subprocess.py", line 574, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
CalledProcessError: Command '('lsb_release', '-a')' returned non-zero exit status 1

so, what's wrong...

**Comment by zeroby0** [comment]
Seems like an error in pip,

Nexcsi needs python 3.8 or greater (https://github.com/nexmonster/nexcsi/blob/main/pyproject.toml), try installing with pip3.
